image: debian/stable
packages:
  - libdrm-dev
  - meson
  - pkgconf
  - python3-setuptools
  - scdoc
sources:
  - https://gitlab.freedesktop.org/emersion/drm_info.git
tasks:
  - setup: |
      cd drm_info
      meson subprojects download
      meson build
  - build: |
      cd drm_info
      ninja -C build
